//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeApi
{
    [Serializable]
    public class RequestMsg : Message
    {
        public const string k_RosMessageName = "unitree_api/Request";
        public override string RosMessageName => k_RosMessageName;

        public RequestHeaderMsg header;
        public string parameter;
        public byte[] binary;

        public RequestMsg()
        {
            this.header = new RequestHeaderMsg();
            this.parameter = "";
            this.binary = new byte[0];
        }

        public RequestMsg(RequestHeaderMsg header, string parameter, byte[] binary)
        {
            this.header = header;
            this.parameter = parameter;
            this.binary = binary;
        }

        public static RequestMsg Deserialize(MessageDeserializer deserializer) => new RequestMsg(deserializer);

        private RequestMsg(MessageDeserializer deserializer)
        {
            this.header = RequestHeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.parameter);
            deserializer.Read(out this.binary, sizeof(byte), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.parameter);
            serializer.WriteLength(this.binary);
            serializer.Write(this.binary);
        }

        public override string ToString()
        {
            return "RequestMsg: " +
            "\nheader: " + header.ToString() +
            "\nparameter: " + parameter.ToString() +
            "\nbinary: " + System.String.Join(", ", binary.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
