//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeApi
{
    [Serializable]
    public class RequestHeaderMsg : Message
    {
        public const string k_RosMessageName = "unitree_api/RequestHeader";
        public override string RosMessageName => k_RosMessageName;

        public RequestIdentityMsg identity;
        public RequestLeaseMsg lease;
        public RequestPolicyMsg policy;

        public RequestHeaderMsg()
        {
            this.identity = new RequestIdentityMsg();
            this.lease = new RequestLeaseMsg();
            this.policy = new RequestPolicyMsg();
        }

        public RequestHeaderMsg(RequestIdentityMsg identity, RequestLeaseMsg lease, RequestPolicyMsg policy)
        {
            this.identity = identity;
            this.lease = lease;
            this.policy = policy;
        }

        public static RequestHeaderMsg Deserialize(MessageDeserializer deserializer) => new RequestHeaderMsg(deserializer);

        private RequestHeaderMsg(MessageDeserializer deserializer)
        {
            this.identity = RequestIdentityMsg.Deserialize(deserializer);
            this.lease = RequestLeaseMsg.Deserialize(deserializer);
            this.policy = RequestPolicyMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.identity);
            serializer.Write(this.lease);
            serializer.Write(this.policy);
        }

        public override string ToString()
        {
            return "RequestHeaderMsg: " +
            "\nidentity: " + identity.ToString() +
            "\nlease: " + lease.ToString() +
            "\npolicy: " + policy.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
