//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeApi
{
    [Serializable]
    public class RequestLeaseMsg : Message
    {
        public const string k_RosMessageName = "unitree_api/RequestLease";
        public override string RosMessageName => k_RosMessageName;

        public long id;

        public RequestLeaseMsg()
        {
            this.id = 0;
        }

        public RequestLeaseMsg(long id)
        {
            this.id = id;
        }

        public static RequestLeaseMsg Deserialize(MessageDeserializer deserializer) => new RequestLeaseMsg(deserializer);

        private RequestLeaseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
        }

        public override string ToString()
        {
            return "RequestLeaseMsg: " +
            "\nid: " + id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
