//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeApi
{
    [Serializable]
    public class RequestIdentityMsg : Message
    {
        public const string k_RosMessageName = "unitree_api/RequestIdentity";
        public override string RosMessageName => k_RosMessageName;

        public long id;
        public long api_id;

        public RequestIdentityMsg()
        {
            this.id = 0;
            this.api_id = 0;
        }

        public RequestIdentityMsg(long id, long api_id)
        {
            this.id = id;
            this.api_id = api_id;
        }

        public static RequestIdentityMsg Deserialize(MessageDeserializer deserializer) => new RequestIdentityMsg(deserializer);

        private RequestIdentityMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.api_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.api_id);
        }

        public override string ToString()
        {
            return "RequestIdentityMsg: " +
            "\nid: " + id.ToString() +
            "\napi_id: " + api_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
