//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeApi
{
    [Serializable]
    public class RequestPolicyMsg : Message
    {
        public const string k_RosMessageName = "unitree_api/RequestPolicy";
        public override string RosMessageName => k_RosMessageName;

        public int priority;
        public bool noreply;

        public RequestPolicyMsg()
        {
            this.priority = 0;
            this.noreply = false;
        }

        public RequestPolicyMsg(int priority, bool noreply)
        {
            this.priority = priority;
            this.noreply = noreply;
        }

        public static RequestPolicyMsg Deserialize(MessageDeserializer deserializer) => new RequestPolicyMsg(deserializer);

        private RequestPolicyMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.priority);
            deserializer.Read(out this.noreply);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.priority);
            serializer.Write(this.noreply);
        }

        public override string ToString()
        {
            return "RequestPolicyMsg: " +
            "\npriority: " + priority.ToString() +
            "\nnoreply: " + noreply.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
