//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeApi
{
    [Serializable]
    public class ResponseHeaderMsg : Message
    {
        public const string k_RosMessageName = "unitree_api/ResponseHeader";
        public override string RosMessageName => k_RosMessageName;

        public RequestIdentityMsg identity;
        public ResponseStatusMsg status;

        public ResponseHeaderMsg()
        {
            this.identity = new RequestIdentityMsg();
            this.status = new ResponseStatusMsg();
        }

        public ResponseHeaderMsg(RequestIdentityMsg identity, ResponseStatusMsg status)
        {
            this.identity = identity;
            this.status = status;
        }

        public static ResponseHeaderMsg Deserialize(MessageDeserializer deserializer) => new ResponseHeaderMsg(deserializer);

        private ResponseHeaderMsg(MessageDeserializer deserializer)
        {
            this.identity = RequestIdentityMsg.Deserialize(deserializer);
            this.status = ResponseStatusMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.identity);
            serializer.Write(this.status);
        }

        public override string ToString()
        {
            return "ResponseHeaderMsg: " +
            "\nidentity: " + identity.ToString() +
            "\nstatus: " + status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
