//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeApi
{
    [Serializable]
    public class ResponseStatusMsg : Message
    {
        public const string k_RosMessageName = "unitree_api/ResponseStatus";
        public override string RosMessageName => k_RosMessageName;

        public int code;

        public ResponseStatusMsg()
        {
            this.code = 0;
        }

        public ResponseStatusMsg(int code)
        {
            this.code = code;
        }

        public static ResponseStatusMsg Deserialize(MessageDeserializer deserializer) => new ResponseStatusMsg(deserializer);

        private ResponseStatusMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.code);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.code);
        }

        public override string ToString()
        {
            return "ResponseStatusMsg: " +
            "\ncode: " + code.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
