//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeApi
{
    [Serializable]
    public class ResponseMsg : Message
    {
        public const string k_RosMessageName = "unitree_api/Response";
        public override string RosMessageName => k_RosMessageName;

        public ResponseHeaderMsg header;
        public string data;
        public sbyte[] binary;

        public ResponseMsg()
        {
            this.header = new ResponseHeaderMsg();
            this.data = "";
            this.binary = new sbyte[0];
        }

        public ResponseMsg(ResponseHeaderMsg header, string data, sbyte[] binary)
        {
            this.header = header;
            this.data = data;
            this.binary = binary;
        }

        public static ResponseMsg Deserialize(MessageDeserializer deserializer) => new ResponseMsg(deserializer);

        private ResponseMsg(MessageDeserializer deserializer)
        {
            this.header = ResponseHeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.data);
            deserializer.Read(out this.binary, sizeof(sbyte), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.data);
            serializer.WriteLength(this.binary);
            serializer.Write(this.binary);
        }

        public override string ToString()
        {
            return "ResponseMsg: " +
            "\nheader: " + header.ToString() +
            "\ndata: " + data.ToString() +
            "\nbinary: " + System.String.Join(", ", binary.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
