behaviors:
  gewu:
    checkpoint_interval: 400000
    hyperparameters: {batch_size: 2048, beta: 0.005, beta_schedule: linear, buffer_size: 20480,
      epsilon: 0.2, epsilon_schedule: linear, lambd: 0.95, learning_rate: 0.0003,
      learning_rate_schedule: linear, num_epoch: 3}
    keep_checkpoints: 5
    max_steps: 20000000
    network_settings: {deterministic: false, goal_conditioning_type: hyper, hidden_units: 512,
      normalize: true, num_layers: 3, vis_encode_type: simple}
    reward_signals:
      extrinsic:
        gamma: 0.995
        network_settings: {deterministic: false, goal_conditioning_type: hyper, hidden_units: 128,
          normalize: false, num_layers: 2, vis_encode_type: simple}
        strength: 1.0
    summary_freq: 20000
    threaded: false
    time_horizon: 1000
    trainer_type: ppo