//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeGo
{
    [Serializable]
    public class BmsStateMsg : Message
    {
        public const string k_RosMessageName = "unitree_go/BmsState";
        public override string RosMessageName => k_RosMessageName;

        public byte version_high;
        public byte version_low;
        public byte status;
        public byte soc;
        public int current;
        public ushort cycle;
        public sbyte[] bq_ntc;
        public sbyte[] mcu_ntc;
        public ushort[] cell_vol;

        public BmsStateMsg()
        {
            this.version_high = 0;
            this.version_low = 0;
            this.status = 0;
            this.soc = 0;
            this.current = 0;
            this.cycle = 0;
            this.bq_ntc = new sbyte[2];
            this.mcu_ntc = new sbyte[2];
            this.cell_vol = new ushort[15];
        }

        public BmsStateMsg(byte version_high, byte version_low, byte status, byte soc, int current, ushort cycle, sbyte[] bq_ntc, sbyte[] mcu_ntc, ushort[] cell_vol)
        {
            this.version_high = version_high;
            this.version_low = version_low;
            this.status = status;
            this.soc = soc;
            this.current = current;
            this.cycle = cycle;
            this.bq_ntc = bq_ntc;
            this.mcu_ntc = mcu_ntc;
            this.cell_vol = cell_vol;
        }

        public static BmsStateMsg Deserialize(MessageDeserializer deserializer) => new BmsStateMsg(deserializer);

        private BmsStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.version_high);
            deserializer.Read(out this.version_low);
            deserializer.Read(out this.status);
            deserializer.Read(out this.soc);
            deserializer.Read(out this.current);
            deserializer.Read(out this.cycle);
            deserializer.Read(out this.bq_ntc, sizeof(sbyte), 2);
            deserializer.Read(out this.mcu_ntc, sizeof(sbyte), 2);
            deserializer.Read(out this.cell_vol, sizeof(ushort), 15);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.version_high);
            serializer.Write(this.version_low);
            serializer.Write(this.status);
            serializer.Write(this.soc);
            serializer.Write(this.current);
            serializer.Write(this.cycle);
            serializer.Write(this.bq_ntc);
            serializer.Write(this.mcu_ntc);
            serializer.Write(this.cell_vol);
        }

        public override string ToString()
        {
            return "BmsStateMsg: " +
            "\nversion_high: " + version_high.ToString() +
            "\nversion_low: " + version_low.ToString() +
            "\nstatus: " + status.ToString() +
            "\nsoc: " + soc.ToString() +
            "\ncurrent: " + current.ToString() +
            "\ncycle: " + cycle.ToString() +
            "\nbq_ntc: " + System.String.Join(", ", bq_ntc.ToList()) +
            "\nmcu_ntc: " + System.String.Join(", ", mcu_ntc.ToList()) +
            "\ncell_vol: " + System.String.Join(", ", cell_vol.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
