//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeGo
{
    [Serializable]
    public class ErrorMsg : Message
    {
        public const string k_RosMessageName = "unitree_go/Error";
        public override string RosMessageName => k_RosMessageName;

        public uint source;
        public uint state;

        public ErrorMsg()
        {
            this.source = 0;
            this.state = 0;
        }

        public ErrorMsg(uint source, uint state)
        {
            this.source = source;
            this.state = state;
        }

        public static ErrorMsg Deserialize(MessageDeserializer deserializer) => new ErrorMsg(deserializer);

        private ErrorMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.source);
            deserializer.Read(out this.state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.source);
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "ErrorMsg: " +
            "\nsource: " + source.ToString() +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
