//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeGo
{
    [Serializable]
    public class Go2FrontVideoDataMsg : Message
    {
        public const string k_RosMessageName = "unitree_go/Go2FrontVideoData";
        public override string RosMessageName => k_RosMessageName;

        public ulong time_frame;
        public byte[] video720p;
        public byte[] video360p;
        public byte[] video180p;

        public Go2FrontVideoDataMsg()
        {
            this.time_frame = 0;
            this.video720p = new byte[0];
            this.video360p = new byte[0];
            this.video180p = new byte[0];
        }

        public Go2FrontVideoDataMsg(ulong time_frame, byte[] video720p, byte[] video360p, byte[] video180p)
        {
            this.time_frame = time_frame;
            this.video720p = video720p;
            this.video360p = video360p;
            this.video180p = video180p;
        }

        public static Go2FrontVideoDataMsg Deserialize(MessageDeserializer deserializer) => new Go2FrontVideoDataMsg(deserializer);

        private Go2FrontVideoDataMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.time_frame);
            deserializer.Read(out this.video720p, sizeof(byte), deserializer.ReadLength());
            deserializer.Read(out this.video360p, sizeof(byte), deserializer.ReadLength());
            deserializer.Read(out this.video180p, sizeof(byte), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.time_frame);
            serializer.WriteLength(this.video720p);
            serializer.Write(this.video720p);
            serializer.WriteLength(this.video360p);
            serializer.Write(this.video360p);
            serializer.WriteLength(this.video180p);
            serializer.Write(this.video180p);
        }

        public override string ToString()
        {
            return "Go2FrontVideoDataMsg: " +
            "\ntime_frame: " + time_frame.ToString() +
            "\nvideo720p: " + System.String.Join(", ", video720p.ToList()) +
            "\nvideo360p: " + System.String.Join(", ", video360p.ToList()) +
            "\nvideo180p: " + System.String.Join(", ", video180p.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
