//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeGo
{
    [Serializable]
    public class HeightMapMsg : Message
    {
        public const string k_RosMessageName = "unitree_go/HeightMap";
        public override string RosMessageName => k_RosMessageName;

        //  Header
        public double stamp;
        //  timestamp
        public string frame_id;
        //  world frame id
        //  Map info
        public float resolution;
        //  The map resolution [m/cell]
        public uint width;
        //  Map width along x-axis [cells]
        public uint height;
        //  Map height alonge y-axis [cells]
        public float[] origin;
        //  Map frame origin xy-position [m], the xyz-axis direction of map frame is aligned with the world frame
        //  Map data, in x-major order, starting with [0,0], ending with [width, height]
        //  For a cell whose 2d-array-index is [ix, iy]，
        //     its position in world frame is: [ix * resolution + origin[0], iy * resolution + origin[1]]
        //     its cell value is: data[width * iy + ix]
        public float[] data;

        public HeightMapMsg()
        {
            this.stamp = 0.0;
            this.frame_id = "";
            this.resolution = 0.0f;
            this.width = 0;
            this.height = 0;
            this.origin = new float[2];
            this.data = new float[0];
        }

        public HeightMapMsg(double stamp, string frame_id, float resolution, uint width, uint height, float[] origin, float[] data)
        {
            this.stamp = stamp;
            this.frame_id = frame_id;
            this.resolution = resolution;
            this.width = width;
            this.height = height;
            this.origin = origin;
            this.data = data;
        }

        public static HeightMapMsg Deserialize(MessageDeserializer deserializer) => new HeightMapMsg(deserializer);

        private HeightMapMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.stamp);
            deserializer.Read(out this.frame_id);
            deserializer.Read(out this.resolution);
            deserializer.Read(out this.width);
            deserializer.Read(out this.height);
            deserializer.Read(out this.origin, sizeof(float), 2);
            deserializer.Read(out this.data, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stamp);
            serializer.Write(this.frame_id);
            serializer.Write(this.resolution);
            serializer.Write(this.width);
            serializer.Write(this.height);
            serializer.Write(this.origin);
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "HeightMapMsg: " +
            "\nstamp: " + stamp.ToString() +
            "\nframe_id: " + frame_id.ToString() +
            "\nresolution: " + resolution.ToString() +
            "\nwidth: " + width.ToString() +
            "\nheight: " + height.ToString() +
            "\norigin: " + System.String.Join(", ", origin.ToList()) +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
