//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeGo
{
    [Serializable]
    public class InterfaceConfigMsg : Message
    {
        public const string k_RosMessageName = "unitree_go/InterfaceConfig";
        public override string RosMessageName => k_RosMessageName;

        public byte mode;
        public byte value;
        public byte[] reserve;

        public InterfaceConfigMsg()
        {
            this.mode = 0;
            this.value = 0;
            this.reserve = new byte[2];
        }

        public InterfaceConfigMsg(byte mode, byte value, byte[] reserve)
        {
            this.mode = mode;
            this.value = value;
            this.reserve = reserve;
        }

        public static InterfaceConfigMsg Deserialize(MessageDeserializer deserializer) => new InterfaceConfigMsg(deserializer);

        private InterfaceConfigMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mode);
            deserializer.Read(out this.value);
            deserializer.Read(out this.reserve, sizeof(byte), 2);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mode);
            serializer.Write(this.value);
            serializer.Write(this.reserve);
        }

        public override string ToString()
        {
            return "InterfaceConfigMsg: " +
            "\nmode: " + mode.ToString() +
            "\nvalue: " + value.ToString() +
            "\nreserve: " + System.String.Join(", ", reserve.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
