//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeGo
{
    [Serializable]
    public class LidarStateMsg : Message
    {
        public const string k_RosMessageName = "unitree_go/LidarState";
        public override string RosMessageName => k_RosMessageName;

        public double stamp;
        public string firmware_version;
        public string software_version;
        public string sdk_version;
        public float sys_rotation_speed;
        public float com_rotation_speed;
        public byte error_state;
        public float cloud_frequency;
        public float cloud_packet_loss_rate;
        public uint cloud_size;
        public uint cloud_scan_num;
        public float imu_frequency;
        public float imu_packet_loss_rate;
        public float[] imu_rpy;
        public double serial_recv_stamp;
        public uint serial_buffer_size;
        public uint serial_buffer_read;

        public LidarStateMsg()
        {
            this.stamp = 0.0;
            this.firmware_version = "";
            this.software_version = "";
            this.sdk_version = "";
            this.sys_rotation_speed = 0.0f;
            this.com_rotation_speed = 0.0f;
            this.error_state = 0;
            this.cloud_frequency = 0.0f;
            this.cloud_packet_loss_rate = 0.0f;
            this.cloud_size = 0;
            this.cloud_scan_num = 0;
            this.imu_frequency = 0.0f;
            this.imu_packet_loss_rate = 0.0f;
            this.imu_rpy = new float[3];
            this.serial_recv_stamp = 0.0;
            this.serial_buffer_size = 0;
            this.serial_buffer_read = 0;
        }

        public LidarStateMsg(double stamp, string firmware_version, string software_version, string sdk_version, float sys_rotation_speed, float com_rotation_speed, byte error_state, float cloud_frequency, float cloud_packet_loss_rate, uint cloud_size, uint cloud_scan_num, float imu_frequency, float imu_packet_loss_rate, float[] imu_rpy, double serial_recv_stamp, uint serial_buffer_size, uint serial_buffer_read)
        {
            this.stamp = stamp;
            this.firmware_version = firmware_version;
            this.software_version = software_version;
            this.sdk_version = sdk_version;
            this.sys_rotation_speed = sys_rotation_speed;
            this.com_rotation_speed = com_rotation_speed;
            this.error_state = error_state;
            this.cloud_frequency = cloud_frequency;
            this.cloud_packet_loss_rate = cloud_packet_loss_rate;
            this.cloud_size = cloud_size;
            this.cloud_scan_num = cloud_scan_num;
            this.imu_frequency = imu_frequency;
            this.imu_packet_loss_rate = imu_packet_loss_rate;
            this.imu_rpy = imu_rpy;
            this.serial_recv_stamp = serial_recv_stamp;
            this.serial_buffer_size = serial_buffer_size;
            this.serial_buffer_read = serial_buffer_read;
        }

        public static LidarStateMsg Deserialize(MessageDeserializer deserializer) => new LidarStateMsg(deserializer);

        private LidarStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.stamp);
            deserializer.Read(out this.firmware_version);
            deserializer.Read(out this.software_version);
            deserializer.Read(out this.sdk_version);
            deserializer.Read(out this.sys_rotation_speed);
            deserializer.Read(out this.com_rotation_speed);
            deserializer.Read(out this.error_state);
            deserializer.Read(out this.cloud_frequency);
            deserializer.Read(out this.cloud_packet_loss_rate);
            deserializer.Read(out this.cloud_size);
            deserializer.Read(out this.cloud_scan_num);
            deserializer.Read(out this.imu_frequency);
            deserializer.Read(out this.imu_packet_loss_rate);
            deserializer.Read(out this.imu_rpy, sizeof(float), 3);
            deserializer.Read(out this.serial_recv_stamp);
            deserializer.Read(out this.serial_buffer_size);
            deserializer.Read(out this.serial_buffer_read);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stamp);
            serializer.Write(this.firmware_version);
            serializer.Write(this.software_version);
            serializer.Write(this.sdk_version);
            serializer.Write(this.sys_rotation_speed);
            serializer.Write(this.com_rotation_speed);
            serializer.Write(this.error_state);
            serializer.Write(this.cloud_frequency);
            serializer.Write(this.cloud_packet_loss_rate);
            serializer.Write(this.cloud_size);
            serializer.Write(this.cloud_scan_num);
            serializer.Write(this.imu_frequency);
            serializer.Write(this.imu_packet_loss_rate);
            serializer.Write(this.imu_rpy);
            serializer.Write(this.serial_recv_stamp);
            serializer.Write(this.serial_buffer_size);
            serializer.Write(this.serial_buffer_read);
        }

        public override string ToString()
        {
            return "LidarStateMsg: " +
            "\nstamp: " + stamp.ToString() +
            "\nfirmware_version: " + firmware_version.ToString() +
            "\nsoftware_version: " + software_version.ToString() +
            "\nsdk_version: " + sdk_version.ToString() +
            "\nsys_rotation_speed: " + sys_rotation_speed.ToString() +
            "\ncom_rotation_speed: " + com_rotation_speed.ToString() +
            "\nerror_state: " + error_state.ToString() +
            "\ncloud_frequency: " + cloud_frequency.ToString() +
            "\ncloud_packet_loss_rate: " + cloud_packet_loss_rate.ToString() +
            "\ncloud_size: " + cloud_size.ToString() +
            "\ncloud_scan_num: " + cloud_scan_num.ToString() +
            "\nimu_frequency: " + imu_frequency.ToString() +
            "\nimu_packet_loss_rate: " + imu_packet_loss_rate.ToString() +
            "\nimu_rpy: " + System.String.Join(", ", imu_rpy.ToList()) +
            "\nserial_recv_stamp: " + serial_recv_stamp.ToString() +
            "\nserial_buffer_size: " + serial_buffer_size.ToString() +
            "\nserial_buffer_read: " + serial_buffer_read.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
