//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeGo
{
    [Serializable]
    public class LowCmdMsg : Message
    {
        public const string k_RosMessageName = "unitree_go/LowCmd";
        public override string RosMessageName => k_RosMessageName;

        public byte[] head;
        public byte level_flag;
        public byte frame_reserve;
        public uint[] sn;
        public uint[] version;
        public ushort bandwidth;
        public MotorCmdMsg[] motor_cmd;
        public BmsCmdMsg bms_cmd;
        public byte[] wireless_remote;
        public byte[] led;
        public byte[] fan;
        public byte gpio;
        public uint reserve;
        public uint crc;

        public LowCmdMsg()
        {
            this.head = new byte[2];
            this.level_flag = 0;
            this.frame_reserve = 0;
            this.sn = new uint[2];
            this.version = new uint[2];
            this.bandwidth = 0;
            this.motor_cmd = new MotorCmdMsg[20];
            this.bms_cmd = new BmsCmdMsg();
            this.wireless_remote = new byte[40];
            this.led = new byte[12];
            this.fan = new byte[2];
            this.gpio = 0;
            this.reserve = 0;
            this.crc = 0;
        }

        public LowCmdMsg(byte[] head, byte level_flag, byte frame_reserve, uint[] sn, uint[] version, ushort bandwidth, MotorCmdMsg[] motor_cmd, BmsCmdMsg bms_cmd, byte[] wireless_remote, byte[] led, byte[] fan, byte gpio, uint reserve, uint crc)
        {
            this.head = head;
            this.level_flag = level_flag;
            this.frame_reserve = frame_reserve;
            this.sn = sn;
            this.version = version;
            this.bandwidth = bandwidth;
            this.motor_cmd = motor_cmd;
            this.bms_cmd = bms_cmd;
            this.wireless_remote = wireless_remote;
            this.led = led;
            this.fan = fan;
            this.gpio = gpio;
            this.reserve = reserve;
            this.crc = crc;
        }

        public static LowCmdMsg Deserialize(MessageDeserializer deserializer) => new LowCmdMsg(deserializer);

        private LowCmdMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.head, sizeof(byte), 2);
            deserializer.Read(out this.level_flag);
            deserializer.Read(out this.frame_reserve);
            deserializer.Read(out this.sn, sizeof(uint), 2);
            deserializer.Read(out this.version, sizeof(uint), 2);
            deserializer.Read(out this.bandwidth);
            deserializer.Read(out this.motor_cmd, MotorCmdMsg.Deserialize, 20);
            this.bms_cmd = BmsCmdMsg.Deserialize(deserializer);
            deserializer.Read(out this.wireless_remote, sizeof(byte), 40);
            deserializer.Read(out this.led, sizeof(byte), 12);
            deserializer.Read(out this.fan, sizeof(byte), 2);
            deserializer.Read(out this.gpio);
            deserializer.Read(out this.reserve);
            deserializer.Read(out this.crc);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.head);
            serializer.Write(this.level_flag);
            serializer.Write(this.frame_reserve);
            serializer.Write(this.sn);
            serializer.Write(this.version);
            serializer.Write(this.bandwidth);
            serializer.Write(this.motor_cmd);
            serializer.Write(this.bms_cmd);
            serializer.Write(this.wireless_remote);
            serializer.Write(this.led);
            serializer.Write(this.fan);
            serializer.Write(this.gpio);
            serializer.Write(this.reserve);
            serializer.Write(this.crc);
        }

        public override string ToString()
        {
            return "LowCmdMsg: " +
            "\nhead: " + System.String.Join(", ", head.ToList()) +
            "\nlevel_flag: " + level_flag.ToString() +
            "\nframe_reserve: " + frame_reserve.ToString() +
            "\nsn: " + System.String.Join(", ", sn.ToList()) +
            "\nversion: " + System.String.Join(", ", version.ToList()) +
            "\nbandwidth: " + bandwidth.ToString() +
            "\nmotor_cmd: " + System.String.Join(", ", motor_cmd.ToList()) +
            "\nbms_cmd: " + bms_cmd.ToString() +
            "\nwireless_remote: " + System.String.Join(", ", wireless_remote.ToList()) +
            "\nled: " + System.String.Join(", ", led.ToList()) +
            "\nfan: " + System.String.Join(", ", fan.ToList()) +
            "\ngpio: " + gpio.ToString() +
            "\nreserve: " + reserve.ToString() +
            "\ncrc: " + crc.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
