//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeGo
{
    [Serializable]
    public class MotorStatesMsg : Message
    {
        public const string k_RosMessageName = "unitree_go/MotorStates";
        public override string RosMessageName => k_RosMessageName;

        public MotorStateMsg[] states;

        public MotorStatesMsg()
        {
            this.states = new MotorStateMsg[0];
        }

        public MotorStatesMsg(MotorStateMsg[] states)
        {
            this.states = states;
        }

        public static MotorStatesMsg Deserialize(MessageDeserializer deserializer) => new MotorStatesMsg(deserializer);

        private MotorStatesMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.states, MotorStateMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.states);
            serializer.Write(this.states);
        }

        public override string ToString()
        {
            return "MotorStatesMsg: " +
            "\nstates: " + System.String.Join(", ", states.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
