//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeGo
{
    [Serializable]
    public class MotorStateMsg : Message
    {
        public const string k_RosMessageName = "unitree_go/MotorState";
        public override string RosMessageName => k_RosMessageName;

        public byte mode;
        public float q;
        public float dq;
        public float ddq;
        public float tau_est;
        public float q_raw;
        public float dq_raw;
        public float ddq_raw;
        public sbyte temperature;
        public uint lost;
        public uint[] reserve;

        public MotorStateMsg()
        {
            this.mode = 0;
            this.q = 0.0f;
            this.dq = 0.0f;
            this.ddq = 0.0f;
            this.tau_est = 0.0f;
            this.q_raw = 0.0f;
            this.dq_raw = 0.0f;
            this.ddq_raw = 0.0f;
            this.temperature = 0;
            this.lost = 0;
            this.reserve = new uint[2];
        }

        public MotorStateMsg(byte mode, float q, float dq, float ddq, float tau_est, float q_raw, float dq_raw, float ddq_raw, sbyte temperature, uint lost, uint[] reserve)
        {
            this.mode = mode;
            this.q = q;
            this.dq = dq;
            this.ddq = ddq;
            this.tau_est = tau_est;
            this.q_raw = q_raw;
            this.dq_raw = dq_raw;
            this.ddq_raw = ddq_raw;
            this.temperature = temperature;
            this.lost = lost;
            this.reserve = reserve;
        }

        public static MotorStateMsg Deserialize(MessageDeserializer deserializer) => new MotorStateMsg(deserializer);

        private MotorStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mode);
            deserializer.Read(out this.q);
            deserializer.Read(out this.dq);
            deserializer.Read(out this.ddq);
            deserializer.Read(out this.tau_est);
            deserializer.Read(out this.q_raw);
            deserializer.Read(out this.dq_raw);
            deserializer.Read(out this.ddq_raw);
            deserializer.Read(out this.temperature);
            deserializer.Read(out this.lost);
            deserializer.Read(out this.reserve, sizeof(uint), 2);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mode);
            serializer.Write(this.q);
            serializer.Write(this.dq);
            serializer.Write(this.ddq);
            serializer.Write(this.tau_est);
            serializer.Write(this.q_raw);
            serializer.Write(this.dq_raw);
            serializer.Write(this.ddq_raw);
            serializer.Write(this.temperature);
            serializer.Write(this.lost);
            serializer.Write(this.reserve);
        }

        public override string ToString()
        {
            return "MotorStateMsg: " +
            "\nmode: " + mode.ToString() +
            "\nq: " + q.ToString() +
            "\ndq: " + dq.ToString() +
            "\nddq: " + ddq.ToString() +
            "\ntau_est: " + tau_est.ToString() +
            "\nq_raw: " + q_raw.ToString() +
            "\ndq_raw: " + dq_raw.ToString() +
            "\nddq_raw: " + ddq_raw.ToString() +
            "\ntemperature: " + temperature.ToString() +
            "\nlost: " + lost.ToString() +
            "\nreserve: " + System.String.Join(", ", reserve.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
