//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeGo
{
    [Serializable]
    public class MotorCmdsMsg : Message
    {
        public const string k_RosMessageName = "unitree_go/MotorCmds";
        public override string RosMessageName => k_RosMessageName;

        public MotorCmdMsg[] cmds;

        public MotorCmdsMsg()
        {
            this.cmds = new MotorCmdMsg[0];
        }

        public MotorCmdsMsg(MotorCmdMsg[] cmds)
        {
            this.cmds = cmds;
        }

        public static MotorCmdsMsg Deserialize(MessageDeserializer deserializer) => new MotorCmdsMsg(deserializer);

        private MotorCmdsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.cmds, MotorCmdMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.cmds);
            serializer.Write(this.cmds);
        }

        public override string ToString()
        {
            return "MotorCmdsMsg: " +
            "\ncmds: " + System.String.Join(", ", cmds.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
