//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeGo
{
    [Serializable]
    public class PathPointMsg : Message
    {
        public const string k_RosMessageName = "unitree_go/PathPoint";
        public override string RosMessageName => k_RosMessageName;

        public float t_from_start;
        public float x;
        public float y;
        public float yaw;
        public float vx;
        public float vy;
        public float vyaw;

        public PathPointMsg()
        {
            this.t_from_start = 0.0f;
            this.x = 0.0f;
            this.y = 0.0f;
            this.yaw = 0.0f;
            this.vx = 0.0f;
            this.vy = 0.0f;
            this.vyaw = 0.0f;
        }

        public PathPointMsg(float t_from_start, float x, float y, float yaw, float vx, float vy, float vyaw)
        {
            this.t_from_start = t_from_start;
            this.x = x;
            this.y = y;
            this.yaw = yaw;
            this.vx = vx;
            this.vy = vy;
            this.vyaw = vyaw;
        }

        public static PathPointMsg Deserialize(MessageDeserializer deserializer) => new PathPointMsg(deserializer);

        private PathPointMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.t_from_start);
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.yaw);
            deserializer.Read(out this.vx);
            deserializer.Read(out this.vy);
            deserializer.Read(out this.vyaw);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.t_from_start);
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.yaw);
            serializer.Write(this.vx);
            serializer.Write(this.vy);
            serializer.Write(this.vyaw);
        }

        public override string ToString()
        {
            return "PathPointMsg: " +
            "\nt_from_start: " + t_from_start.ToString() +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nyaw: " + yaw.ToString() +
            "\nvx: " + vx.ToString() +
            "\nvy: " + vy.ToString() +
            "\nvyaw: " + vyaw.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
