//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeGo
{
    [Serializable]
    public class ReqMsg : Message
    {
        public const string k_RosMessageName = "unitree_go/Req";
        public override string RosMessageName => k_RosMessageName;

        public string uuid;
        public string body;

        public ReqMsg()
        {
            this.uuid = "";
            this.body = "";
        }

        public ReqMsg(string uuid, string body)
        {
            this.uuid = uuid;
            this.body = body;
        }

        public static ReqMsg Deserialize(MessageDeserializer deserializer) => new ReqMsg(deserializer);

        private ReqMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.uuid);
            deserializer.Read(out this.body);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.uuid);
            serializer.Write(this.body);
        }

        public override string ToString()
        {
            return "ReqMsg: " +
            "\nuuid: " + uuid.ToString() +
            "\nbody: " + body.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
