//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeGo
{
    [Serializable]
    public class ResMsg : Message
    {
        public const string k_RosMessageName = "unitree_go/Res";
        public override string RosMessageName => k_RosMessageName;

        public string uuid;
        public byte[] data;
        public string body;

        public ResMsg()
        {
            this.uuid = "";
            this.data = new byte[0];
            this.body = "";
        }

        public ResMsg(string uuid, byte[] data, string body)
        {
            this.uuid = uuid;
            this.data = data;
            this.body = body;
        }

        public static ResMsg Deserialize(MessageDeserializer deserializer) => new ResMsg(deserializer);

        private ResMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.uuid);
            deserializer.Read(out this.data, sizeof(byte), deserializer.ReadLength());
            deserializer.Read(out this.body);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.uuid);
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
            serializer.Write(this.body);
        }

        public override string ToString()
        {
            return "ResMsg: " +
            "\nuuid: " + uuid.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList()) +
            "\nbody: " + body.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
