//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeGo
{
    [Serializable]
    public class SportModeCmdMsg : Message
    {
        public const string k_RosMessageName = "unitree_go/SportModeCmd";
        public override string RosMessageName => k_RosMessageName;

        public byte mode;
        public byte gait_type;
        public byte speed_level;
        public float foot_raise_height;
        public float body_height;
        public float[] position;
        public float[] euler;
        public float[] velocity;
        public float yaw_speed;
        public BmsCmdMsg bms_cmd;
        public PathPointMsg[] path_point;

        public SportModeCmdMsg()
        {
            this.mode = 0;
            this.gait_type = 0;
            this.speed_level = 0;
            this.foot_raise_height = 0.0f;
            this.body_height = 0.0f;
            this.position = new float[2];
            this.euler = new float[3];
            this.velocity = new float[2];
            this.yaw_speed = 0.0f;
            this.bms_cmd = new BmsCmdMsg();
            this.path_point = new PathPointMsg[30];
        }

        public SportModeCmdMsg(byte mode, byte gait_type, byte speed_level, float foot_raise_height, float body_height, float[] position, float[] euler, float[] velocity, float yaw_speed, BmsCmdMsg bms_cmd, PathPointMsg[] path_point)
        {
            this.mode = mode;
            this.gait_type = gait_type;
            this.speed_level = speed_level;
            this.foot_raise_height = foot_raise_height;
            this.body_height = body_height;
            this.position = position;
            this.euler = euler;
            this.velocity = velocity;
            this.yaw_speed = yaw_speed;
            this.bms_cmd = bms_cmd;
            this.path_point = path_point;
        }

        public static SportModeCmdMsg Deserialize(MessageDeserializer deserializer) => new SportModeCmdMsg(deserializer);

        private SportModeCmdMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mode);
            deserializer.Read(out this.gait_type);
            deserializer.Read(out this.speed_level);
            deserializer.Read(out this.foot_raise_height);
            deserializer.Read(out this.body_height);
            deserializer.Read(out this.position, sizeof(float), 2);
            deserializer.Read(out this.euler, sizeof(float), 3);
            deserializer.Read(out this.velocity, sizeof(float), 2);
            deserializer.Read(out this.yaw_speed);
            this.bms_cmd = BmsCmdMsg.Deserialize(deserializer);
            deserializer.Read(out this.path_point, PathPointMsg.Deserialize, 30);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mode);
            serializer.Write(this.gait_type);
            serializer.Write(this.speed_level);
            serializer.Write(this.foot_raise_height);
            serializer.Write(this.body_height);
            serializer.Write(this.position);
            serializer.Write(this.euler);
            serializer.Write(this.velocity);
            serializer.Write(this.yaw_speed);
            serializer.Write(this.bms_cmd);
            serializer.Write(this.path_point);
        }

        public override string ToString()
        {
            return "SportModeCmdMsg: " +
            "\nmode: " + mode.ToString() +
            "\ngait_type: " + gait_type.ToString() +
            "\nspeed_level: " + speed_level.ToString() +
            "\nfoot_raise_height: " + foot_raise_height.ToString() +
            "\nbody_height: " + body_height.ToString() +
            "\nposition: " + System.String.Join(", ", position.ToList()) +
            "\neuler: " + System.String.Join(", ", euler.ToList()) +
            "\nvelocity: " + System.String.Join(", ", velocity.ToList()) +
            "\nyaw_speed: " + yaw_speed.ToString() +
            "\nbms_cmd: " + bms_cmd.ToString() +
            "\npath_point: " + System.String.Join(", ", path_point.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
