//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeGo
{
    [Serializable]
    public class UwbSwitchMsg : Message
    {
        public const string k_RosMessageName = "unitree_go/UwbSwitch";
        public override string RosMessageName => k_RosMessageName;

        public byte enabled;

        public UwbSwitchMsg()
        {
            this.enabled = 0;
        }

        public UwbSwitchMsg(byte enabled)
        {
            this.enabled = enabled;
        }

        public static UwbSwitchMsg Deserialize(MessageDeserializer deserializer) => new UwbSwitchMsg(deserializer);

        private UwbSwitchMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.enabled);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.enabled);
        }

        public override string ToString()
        {
            return "UwbSwitchMsg: " +
            "\nenabled: " + enabled.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
