//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeGo
{
    [Serializable]
    public class WirelessControllerMsg : Message
    {
        public const string k_RosMessageName = "unitree_go/WirelessController";
        public override string RosMessageName => k_RosMessageName;

        public float lx;
        public float ly;
        public float rx;
        public float ry;
        public ushort keys;

        public WirelessControllerMsg()
        {
            this.lx = 0.0f;
            this.ly = 0.0f;
            this.rx = 0.0f;
            this.ry = 0.0f;
            this.keys = 0;
        }

        public WirelessControllerMsg(float lx, float ly, float rx, float ry, ushort keys)
        {
            this.lx = lx;
            this.ly = ly;
            this.rx = rx;
            this.ry = ry;
            this.keys = keys;
        }

        public static WirelessControllerMsg Deserialize(MessageDeserializer deserializer) => new WirelessControllerMsg(deserializer);

        private WirelessControllerMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.lx);
            deserializer.Read(out this.ly);
            deserializer.Read(out this.rx);
            deserializer.Read(out this.ry);
            deserializer.Read(out this.keys);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.lx);
            serializer.Write(this.ly);
            serializer.Write(this.rx);
            serializer.Write(this.ry);
            serializer.Write(this.keys);
        }

        public override string ToString()
        {
            return "WirelessControllerMsg: " +
            "\nlx: " + lx.ToString() +
            "\nly: " + ly.ToString() +
            "\nrx: " + rx.ToString() +
            "\nry: " + ry.ToString() +
            "\nkeys: " + keys.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
