//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeHg
{
    [Serializable]
    public class BmsCmdMsg : Message
    {
        public const string k_RosMessageName = "unitree_hg/BmsCmd";
        public override string RosMessageName => k_RosMessageName;

        public byte cmd;
        public byte[] reserve;

        public BmsCmdMsg()
        {
            this.cmd = 0;
            this.reserve = new byte[40];
        }

        public BmsCmdMsg(byte cmd, byte[] reserve)
        {
            this.cmd = cmd;
            this.reserve = reserve;
        }

        public static BmsCmdMsg Deserialize(MessageDeserializer deserializer) => new BmsCmdMsg(deserializer);

        private BmsCmdMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.cmd);
            deserializer.Read(out this.reserve, sizeof(byte), 40);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cmd);
            serializer.Write(this.reserve);
        }

        public override string ToString()
        {
            return "BmsCmdMsg: " +
            "\ncmd: " + cmd.ToString() +
            "\nreserve: " + System.String.Join(", ", reserve.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
