//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeHg
{
    [Serializable]
    public class BmsStateMsg : Message
    {
        public const string k_RosMessageName = "unitree_hg/BmsState";
        public override string RosMessageName => k_RosMessageName;

        public byte version_high;
        public byte version_low;
        public byte fn;
        public ushort[] cell_vol;
        public uint[] bmsvoltage;
        public int current;
        public byte soc;
        public byte soh;
        public short[] temperature;
        public ushort cycle;
        public ushort manufacturer_date;
        public uint[] bmsstate;
        public uint[] reserve;

        public BmsStateMsg()
        {
            this.version_high = 0;
            this.version_low = 0;
            this.fn = 0;
            this.cell_vol = new ushort[40];
            this.bmsvoltage = new uint[3];
            this.current = 0;
            this.soc = 0;
            this.soh = 0;
            this.temperature = new short[12];
            this.cycle = 0;
            this.manufacturer_date = 0;
            this.bmsstate = new uint[5];
            this.reserve = new uint[3];
        }

        public BmsStateMsg(byte version_high, byte version_low, byte fn, ushort[] cell_vol, uint[] bmsvoltage, int current, byte soc, byte soh, short[] temperature, ushort cycle, ushort manufacturer_date, uint[] bmsstate, uint[] reserve)
        {
            this.version_high = version_high;
            this.version_low = version_low;
            this.fn = fn;
            this.cell_vol = cell_vol;
            this.bmsvoltage = bmsvoltage;
            this.current = current;
            this.soc = soc;
            this.soh = soh;
            this.temperature = temperature;
            this.cycle = cycle;
            this.manufacturer_date = manufacturer_date;
            this.bmsstate = bmsstate;
            this.reserve = reserve;
        }

        public static BmsStateMsg Deserialize(MessageDeserializer deserializer) => new BmsStateMsg(deserializer);

        private BmsStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.version_high);
            deserializer.Read(out this.version_low);
            deserializer.Read(out this.fn);
            deserializer.Read(out this.cell_vol, sizeof(ushort), 40);
            deserializer.Read(out this.bmsvoltage, sizeof(uint), 3);
            deserializer.Read(out this.current);
            deserializer.Read(out this.soc);
            deserializer.Read(out this.soh);
            deserializer.Read(out this.temperature, sizeof(short), 12);
            deserializer.Read(out this.cycle);
            deserializer.Read(out this.manufacturer_date);
            deserializer.Read(out this.bmsstate, sizeof(uint), 5);
            deserializer.Read(out this.reserve, sizeof(uint), 3);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.version_high);
            serializer.Write(this.version_low);
            serializer.Write(this.fn);
            serializer.Write(this.cell_vol);
            serializer.Write(this.bmsvoltage);
            serializer.Write(this.current);
            serializer.Write(this.soc);
            serializer.Write(this.soh);
            serializer.Write(this.temperature);
            serializer.Write(this.cycle);
            serializer.Write(this.manufacturer_date);
            serializer.Write(this.bmsstate);
            serializer.Write(this.reserve);
        }

        public override string ToString()
        {
            return "BmsStateMsg: " +
            "\nversion_high: " + version_high.ToString() +
            "\nversion_low: " + version_low.ToString() +
            "\nfn: " + fn.ToString() +
            "\ncell_vol: " + System.String.Join(", ", cell_vol.ToList()) +
            "\nbmsvoltage: " + System.String.Join(", ", bmsvoltage.ToList()) +
            "\ncurrent: " + current.ToString() +
            "\nsoc: " + soc.ToString() +
            "\nsoh: " + soh.ToString() +
            "\ntemperature: " + System.String.Join(", ", temperature.ToList()) +
            "\ncycle: " + cycle.ToString() +
            "\nmanufacturer_date: " + manufacturer_date.ToString() +
            "\nbmsstate: " + System.String.Join(", ", bmsstate.ToList()) +
            "\nreserve: " + System.String.Join(", ", reserve.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
