//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeHg
{
    [Serializable]
    public class HandCmdMsg : Message
    {
        public const string k_RosMessageName = "unitree_hg/HandCmd";
        public override string RosMessageName => k_RosMessageName;

        public MotorCmdMsg[] motor_cmd;

        public HandCmdMsg()
        {
            this.motor_cmd = new MotorCmdMsg[0];
        }

        public HandCmdMsg(MotorCmdMsg[] motor_cmd)
        {
            this.motor_cmd = motor_cmd;
        }

        public static HandCmdMsg Deserialize(MessageDeserializer deserializer) => new HandCmdMsg(deserializer);

        private HandCmdMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.motor_cmd, MotorCmdMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.motor_cmd);
            serializer.Write(this.motor_cmd);
        }

        public override string ToString()
        {
            return "HandCmdMsg: " +
            "\nmotor_cmd: " + System.String.Join(", ", motor_cmd.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
