//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeHg
{
    [Serializable]
    public class HandStateMsg : Message
    {
        public const string k_RosMessageName = "unitree_hg/HandState";
        public override string RosMessageName => k_RosMessageName;

        public MotorStateMsg[] motor_state;
        public IMUStateMsg imu_state;
        public PressSensorStateMsg[] press_sensor_state;
        public float power_v;
        public float power_a;
        public uint[] reserve;

        public HandStateMsg()
        {
            this.motor_state = new MotorStateMsg[0];
            this.imu_state = new IMUStateMsg();
            this.press_sensor_state = new PressSensorStateMsg[0];
            this.power_v = 0.0f;
            this.power_a = 0.0f;
            this.reserve = new uint[2];
        }

        public HandStateMsg(MotorStateMsg[] motor_state, IMUStateMsg imu_state, PressSensorStateMsg[] press_sensor_state, float power_v, float power_a, uint[] reserve)
        {
            this.motor_state = motor_state;
            this.imu_state = imu_state;
            this.press_sensor_state = press_sensor_state;
            this.power_v = power_v;
            this.power_a = power_a;
            this.reserve = reserve;
        }

        public static HandStateMsg Deserialize(MessageDeserializer deserializer) => new HandStateMsg(deserializer);

        private HandStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.motor_state, MotorStateMsg.Deserialize, deserializer.ReadLength());
            this.imu_state = IMUStateMsg.Deserialize(deserializer);
            deserializer.Read(out this.press_sensor_state, PressSensorStateMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.power_v);
            deserializer.Read(out this.power_a);
            deserializer.Read(out this.reserve, sizeof(uint), 2);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.motor_state);
            serializer.Write(this.motor_state);
            serializer.Write(this.imu_state);
            serializer.WriteLength(this.press_sensor_state);
            serializer.Write(this.press_sensor_state);
            serializer.Write(this.power_v);
            serializer.Write(this.power_a);
            serializer.Write(this.reserve);
        }

        public override string ToString()
        {
            return "HandStateMsg: " +
            "\nmotor_state: " + System.String.Join(", ", motor_state.ToList()) +
            "\nimu_state: " + imu_state.ToString() +
            "\npress_sensor_state: " + System.String.Join(", ", press_sensor_state.ToList()) +
            "\npower_v: " + power_v.ToString() +
            "\npower_a: " + power_a.ToString() +
            "\nreserve: " + System.String.Join(", ", reserve.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
