//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeHg
{
    [Serializable]
    public class LowCmdMsg : Message
    {
        public const string k_RosMessageName = "unitree_hg/LowCmd";
        public override string RosMessageName => k_RosMessageName;

        public byte mode_pr;
        public byte mode_machine;
        public MotorCmdMsg[] motor_cmd;
        public uint[] reserve;
        public uint crc;

        public LowCmdMsg()
        {
            this.mode_pr = 0;
            this.mode_machine = 0;
            this.motor_cmd = new MotorCmdMsg[35];
            this.reserve = new uint[4];
            this.crc = 0;
        }

        public LowCmdMsg(byte mode_pr, byte mode_machine, MotorCmdMsg[] motor_cmd, uint[] reserve, uint crc)
        {
            this.mode_pr = mode_pr;
            this.mode_machine = mode_machine;
            this.motor_cmd = motor_cmd;
            this.reserve = reserve;
            this.crc = crc;
        }

        public static LowCmdMsg Deserialize(MessageDeserializer deserializer) => new LowCmdMsg(deserializer);

        private LowCmdMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mode_pr);
            deserializer.Read(out this.mode_machine);
            deserializer.Read(out this.motor_cmd, MotorCmdMsg.Deserialize, 35);
            deserializer.Read(out this.reserve, sizeof(uint), 4);
            deserializer.Read(out this.crc);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mode_pr);
            serializer.Write(this.mode_machine);
            serializer.Write(this.motor_cmd);
            serializer.Write(this.reserve);
            serializer.Write(this.crc);
        }

        public override string ToString()
        {
            return "LowCmdMsg: " +
            "\nmode_pr: " + mode_pr.ToString() +
            "\nmode_machine: " + mode_machine.ToString() +
            "\nmotor_cmd: " + System.String.Join(", ", motor_cmd.ToList()) +
            "\nreserve: " + System.String.Join(", ", reserve.ToList()) +
            "\ncrc: " + crc.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
