//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeHg
{
    [Serializable]
    public class LowStateMsg : Message
    {
        public const string k_RosMessageName = "unitree_hg/LowState";
        public override string RosMessageName => k_RosMessageName;

        public uint[] version;
        public byte mode_pr;
        public byte mode_machine;
        public uint tick;
        public IMUStateMsg imu_state;
        public MotorStateMsg[] motor_state;
        public byte[] wireless_remote;
        public uint[] reserve;
        public uint crc;

        public LowStateMsg()
        {
            this.version = new uint[2];
            this.mode_pr = 0;
            this.mode_machine = 0;
            this.tick = 0;
            this.imu_state = new IMUStateMsg();
            this.motor_state = new MotorStateMsg[35];
            this.wireless_remote = new byte[40];
            this.reserve = new uint[4];
            this.crc = 0;
        }

        public LowStateMsg(uint[] version, byte mode_pr, byte mode_machine, uint tick, IMUStateMsg imu_state, MotorStateMsg[] motor_state, byte[] wireless_remote, uint[] reserve, uint crc)
        {
            this.version = version;
            this.mode_pr = mode_pr;
            this.mode_machine = mode_machine;
            this.tick = tick;
            this.imu_state = imu_state;
            this.motor_state = motor_state;
            this.wireless_remote = wireless_remote;
            this.reserve = reserve;
            this.crc = crc;
        }

        public static LowStateMsg Deserialize(MessageDeserializer deserializer) => new LowStateMsg(deserializer);

        private LowStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.version, sizeof(uint), 2);
            deserializer.Read(out this.mode_pr);
            deserializer.Read(out this.mode_machine);
            deserializer.Read(out this.tick);
            this.imu_state = IMUStateMsg.Deserialize(deserializer);
            deserializer.Read(out this.motor_state, MotorStateMsg.Deserialize, 35);
            deserializer.Read(out this.wireless_remote, sizeof(byte), 40);
            deserializer.Read(out this.reserve, sizeof(uint), 4);
            deserializer.Read(out this.crc);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.version);
            serializer.Write(this.mode_pr);
            serializer.Write(this.mode_machine);
            serializer.Write(this.tick);
            serializer.Write(this.imu_state);
            serializer.Write(this.motor_state);
            serializer.Write(this.wireless_remote);
            serializer.Write(this.reserve);
            serializer.Write(this.crc);
        }

        public override string ToString()
        {
            return "LowStateMsg: " +
            "\nversion: " + System.String.Join(", ", version.ToList()) +
            "\nmode_pr: " + mode_pr.ToString() +
            "\nmode_machine: " + mode_machine.ToString() +
            "\ntick: " + tick.ToString() +
            "\nimu_state: " + imu_state.ToString() +
            "\nmotor_state: " + System.String.Join(", ", motor_state.ToList()) +
            "\nwireless_remote: " + System.String.Join(", ", wireless_remote.ToList()) +
            "\nreserve: " + System.String.Join(", ", reserve.ToList()) +
            "\ncrc: " + crc.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
