//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeHg
{
    [Serializable]
    public class MainBoardStateMsg : Message
    {
        public const string k_RosMessageName = "unitree_hg/MainBoardState";
        public override string RosMessageName => k_RosMessageName;

        public ushort[] fan_state;
        public short[] temperature;
        public float[] value;
        public uint[] state;

        public MainBoardStateMsg()
        {
            this.fan_state = new ushort[6];
            this.temperature = new short[6];
            this.value = new float[6];
            this.state = new uint[6];
        }

        public MainBoardStateMsg(ushort[] fan_state, short[] temperature, float[] value, uint[] state)
        {
            this.fan_state = fan_state;
            this.temperature = temperature;
            this.value = value;
            this.state = state;
        }

        public static MainBoardStateMsg Deserialize(MessageDeserializer deserializer) => new MainBoardStateMsg(deserializer);

        private MainBoardStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.fan_state, sizeof(ushort), 6);
            deserializer.Read(out this.temperature, sizeof(short), 6);
            deserializer.Read(out this.value, sizeof(float), 6);
            deserializer.Read(out this.state, sizeof(uint), 6);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.fan_state);
            serializer.Write(this.temperature);
            serializer.Write(this.value);
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "MainBoardStateMsg: " +
            "\nfan_state: " + System.String.Join(", ", fan_state.ToList()) +
            "\ntemperature: " + System.String.Join(", ", temperature.ToList()) +
            "\nvalue: " + System.String.Join(", ", value.ToList()) +
            "\nstate: " + System.String.Join(", ", state.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
