//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeHg
{
    [Serializable]
    public class MotorStateMsg : Message
    {
        public const string k_RosMessageName = "unitree_hg/MotorState";
        public override string RosMessageName => k_RosMessageName;

        public byte mode;
        public float q;
        public float dq;
        public float ddq;
        public float tau_est;
        public short[] temperature;
        public float vol;
        public uint[] sensor;
        public uint motorstate;
        public uint[] reserve;

        public MotorStateMsg()
        {
            this.mode = 0;
            this.q = 0.0f;
            this.dq = 0.0f;
            this.ddq = 0.0f;
            this.tau_est = 0.0f;
            this.temperature = new short[2];
            this.vol = 0.0f;
            this.sensor = new uint[2];
            this.motorstate = 0;
            this.reserve = new uint[4];
        }

        public MotorStateMsg(byte mode, float q, float dq, float ddq, float tau_est, short[] temperature, float vol, uint[] sensor, uint motorstate, uint[] reserve)
        {
            this.mode = mode;
            this.q = q;
            this.dq = dq;
            this.ddq = ddq;
            this.tau_est = tau_est;
            this.temperature = temperature;
            this.vol = vol;
            this.sensor = sensor;
            this.motorstate = motorstate;
            this.reserve = reserve;
        }

        public static MotorStateMsg Deserialize(MessageDeserializer deserializer) => new MotorStateMsg(deserializer);

        private MotorStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mode);
            deserializer.Read(out this.q);
            deserializer.Read(out this.dq);
            deserializer.Read(out this.ddq);
            deserializer.Read(out this.tau_est);
            deserializer.Read(out this.temperature, sizeof(short), 2);
            deserializer.Read(out this.vol);
            deserializer.Read(out this.sensor, sizeof(uint), 2);
            deserializer.Read(out this.motorstate);
            deserializer.Read(out this.reserve, sizeof(uint), 4);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mode);
            serializer.Write(this.q);
            serializer.Write(this.dq);
            serializer.Write(this.ddq);
            serializer.Write(this.tau_est);
            serializer.Write(this.temperature);
            serializer.Write(this.vol);
            serializer.Write(this.sensor);
            serializer.Write(this.motorstate);
            serializer.Write(this.reserve);
        }

        public override string ToString()
        {
            return "MotorStateMsg: " +
            "\nmode: " + mode.ToString() +
            "\nq: " + q.ToString() +
            "\ndq: " + dq.ToString() +
            "\nddq: " + ddq.ToString() +
            "\ntau_est: " + tau_est.ToString() +
            "\ntemperature: " + System.String.Join(", ", temperature.ToList()) +
            "\nvol: " + vol.ToString() +
            "\nsensor: " + System.String.Join(", ", sensor.ToList()) +
            "\nmotorstate: " + motorstate.ToString() +
            "\nreserve: " + System.String.Join(", ", reserve.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
