//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnitreeHg
{
    [Serializable]
    public class PressSensorStateMsg : Message
    {
        public const string k_RosMessageName = "unitree_hg/PressSensorState";
        public override string RosMessageName => k_RosMessageName;

        public float[] pressure;
        public float[] temperature;

        public PressSensorStateMsg()
        {
            this.pressure = new float[12];
            this.temperature = new float[12];
        }

        public PressSensorStateMsg(float[] pressure, float[] temperature)
        {
            this.pressure = pressure;
            this.temperature = temperature;
        }

        public static PressSensorStateMsg Deserialize(MessageDeserializer deserializer) => new PressSensorStateMsg(deserializer);

        private PressSensorStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pressure, sizeof(float), 12);
            deserializer.Read(out this.temperature, sizeof(float), 12);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pressure);
            serializer.Write(this.temperature);
        }

        public override string ToString()
        {
            return "PressSensorStateMsg: " +
            "\npressure: " + System.String.Join(", ", pressure.ToList()) +
            "\ntemperature: " + System.String.Join(", ", temperature.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
